controller_manager:
  ros__parameters:
    update_rate: 50

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    cmd_vel_timeout: 0.5
    wheel_separation: 0.3        # Distance between wheels (adjust to your robot)
    wheel_radius: 0.05           # Wheel radius (meters)
    publish_rate: 50
    use_stamped_vel: false
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
